services:
  db:
    image: 'postgres:12-alpine'
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gobank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_SOURCE=postgresql://root:secret@db:5432/postgres?sslmode=disable
    depends_on:
      - db
    entrypoint: ['/app/wait-for.sh', 'db:5432', '--', '/app/start.sh']
    command: ['/app/main']
